metadata: 
  name: "cfom_dock"
  devices: auto

logger:
  _target_: "pytorch_lightning.loggers.wandb.WandbLogger"
  project: ${metadata.name}
  offline: true

# pretrain:
#   trainer:
#     _target_: "pytorch_lightning.Trainer"
#     devices: ${metadata.devices}
#     num_sanity_val_steps: 1
#     max_epochs: 100
#     check_val_every_n_epoch: 10
#     strategy: 'ddp_find_unused_parameters_true'
#   lightning:
#     _target_: models.dock_lightning.DockLightning
#     lr: 1e-4
#     weight_decay: 1e-4

#   val_dataset:
#     _target_: "datasets.partitioned_fsmol_dock.FsDockDatasetPartitioned"
#     root: "data/fsdock/valid"
#     tasks: "data/fsdock/valid_tasks.csv"
#     random_max_angle: 1

#   train_dataset:
#     _target_: "datasets.partitioned_fsmol_dock.FsDockDatasetPartitioned"
#     root: "data/fsdock/valid"
#     tasks: "data/fsdock/valid_tasks.csv"
#     random_max_angle: 1
#   sampler:
#     _target_: "datasets.custom_distributed_sampler.CustomDistributedSampler"
#     shuffle: true

load_pretrained:
  lightning:
    _target_: models.dock_lightning.DockLightning
  path: '/home/alon.kitin/fs-dock/checkpoints/dock_2025-04-14-22_58_32/epoch=99-val_noise_loss=0.01746.ckpt'  

tokenizer:
  _target_: tokenizers.Tokenizer.from_file
  path: models/configs/smiles_tokenizer.json

model:
  _target_: "models.cfom_dock.CfomDock"
  transformer_encoder: 
  transformer_decoder: 
    _target_: models.transformer.TransformerDecoder
    tokenizer: ${tokenizer}
    embedding_dim: 128
    hidden_size: 128
    nhead: 4
    n_layers: 2
    max_length: 128
  interaction_encoder:
    _target_: models.interaction_encoder.InteractionEncoder
    output_dim: 128
  graph_encoder: 
    _target_: models.graph_encoder.GraphEncoder
    in_channels: 48
    edge_channels: 48
    hidden_channels: [48,48,48,48,48,48,48, 48,64]
    out_channels: 128
    attention_groups: 8
    graph_embedder: 
      _target_: models.graph_embedder.GraphEmbedder
      distance_embed_dim: 16
      cross_distance_embed_dim: 16
      lig_max_radius: 5
      rec_max_radius: 10
      cross_max_distance: 20
      lig_feature_dims: 
        _target_: "datasets.process_chem.features.get_lig_feature_dims"
      lig_edge_feature_dim: 4
      lig_emb_dim: 48
      rec_feature_dims:  
        _target_: "datasets.process_chem.features.get_rec_residue_feature_dims"
      atom_feature_dims:  
        _target_: "datasets.process_chem.features.get_rec_atom_feature_dims"
      prot_emd_dim: 48
      dropout: 0.3
      lm_embedding_dim: 1280
    dropout: 0.1
    max_length: 128


lightning:
  _target_: "models.cfom_dock_lightning.CfomDockLightning"
  lr: 1e-4
  weight_decay: 1e-4
  num_gen_samples: 10
  handle_inactive: penalty

train:
  batch_size: 4
  trainer:
    _target_: "pytorch_lightning.Trainer"
    devices: ${metadata.devices}
    num_sanity_val_steps: 1
    max_epochs: 100
    check_val_every_n_epoch: 5
    strategy: 'ddp_find_unused_parameters_true'


  val_dataset:
    _target_: "datasets.fsmol_dock_clf.FsDockClfDataset"
    root: "data/fsdock/clfs/valid"
    tasks: "data/fsdock/valid_tasks.csv"
    only_inactive: true
    min_roc_auc: 0.70

  train_dataset:
    _target_: "datasets.partitioned_fsmol_dock.FsDockDatasetPartitioned"
    root: "data/fsdock/valid"
    tasks: "data/fsdock/valid_tasks.csv"
    random_max_angle: 1
  sampler:
    _target_: "datasets.custom_distributed_sampler.CustomTaskDistributedSampler"
    shuffle: true
    task_size: 4
    stream: true
